"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hdrs', 'Button', 'Input', 'Label']

# %% ../nbs/00_core.ipynb 2
import fasthtml.common as fh
from fastcore.meta import delegates

# %% ../nbs/00_core.ipynb 5
hdrs = [
    fh.Link(rel="preconnect", href="https://rsms.me/"),
    fh.Link(rel="stylesheet", href="https://rsms.me/inter/inter.css"),
    fh.Script(src="https://unpkg.com/htmx.org@next/dist/htmx.min.js"),
    fh.Script(src="https://cdn.jsdelivr.net/gh/answerdotai/fasthtml-js@1.0.4/fasthtml.js"),
    fh.Script(src="https://cdn.jsdelivr.net/gh/answerdotai/surreal@main/surreal.js"),
    fh.Script(src="https://cdn.jsdelivr.net/gh/gnat/css-scope-inline@main/script.js"),
    fh.Style("""
    :root {
      --zinc-50: #fafafa;
      --zinc-100: #f4f4f5;
      --zinc-200: #e4e4e7;
      --zinc-300: #d4d4d8;
      --zinc-400: #a1a1aa;
      --zinc-500: #71717a;
      --zinc-600: #52525b;
      --zinc-700: #3f3f46;
      --zinc-800: #27272a;
      --zinc-900: #18181b;
      --zinc-950: #09090b;

      --red-50: #fef2f2;
      --red-100: #fee2e2;
      --red-200: #fecaca;
      --red-300: #fca5a5;
      --red-400: #f87171;
      --red-500: #ef4444;
      --red-600: #dc2626;
      --red-700: #b91c1c;
      --red-800: #991b1b;
      --red-900: #7f1d1d;
      --red-950: #450a0a;  

      font-size: 1rem;
      font-family: Inter, sans-serif;
      font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
    }
    @supports (font-variation-settings: normal) {
        :root { font-family: InterVariable, sans-serif; }
    }
    """)
]

# %% ../nbs/00_core.ipynb 8
@delegates(fh.ft_hx, keep=True)
def Button(*args, variant:str = "default", **kwargs):
    styles = """
    me {
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-weight: 500;
        gap: 0.5rem;
        white-space: nowrap;
        height: 2.5rem;
        font-size: 0.875rem;
        line-height: 1.25rem;
        border-radius: 0.5rem;
        padding-left: 1rem;
        padding-right: 1rem;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
        cursor: pointer;
        border-style: solid;
        border-width: 0px;
        background-color: transparent;
    }
    """
    if variant == "default":
        styles += "me { background-color: var(--zinc-800); color: white; border-color: var(--zinc-200); }"
        styles += "me:hover { background-color: var(--zinc-900); }"
    elif variant == "outline":
        styles += "me { background-color: white; color: var(--zinc-700); border-width: 1px; border-color: var(--zinc-200); }"
        styles += "me:hover { background-color: var(--zinc-50); }"
    elif variant == "ghost":
        styles += "me { box-shadow: none; }"
        styles += "me:hover { background-color: var(--zinc-100); }"
    elif variant == "bad":
        styles += "me { color: white; background-color: var(--red-500); }"
        styles += "me:hover { background-color: var(--red-600); }"
    return fh.Button(
        fh.Style(styles), *args, **kwargs)

# %% ../nbs/00_core.ipynb 11
@delegates(fh.ft_hx, keep=True)
def Input(*args, **kwargs):
    styles = f"""
    me {{
        border: 5px solid black;
    }}
    """
    return fh.Input(
        fh.Style(styles), *args, **kwargs)

# %% ../nbs/00_core.ipynb 14
@delegates(fh.ft_hx, keep=True)
def Label(*args, **kwargs):
    styles = f"""
    me {{
        color: green;
    }}
    """
    return fh.Label(
        fh.Style(styles), *args, **kwargs)
